import { NextRequest, NextResponse } from 'next/server';
import { createServerClient } from '@supabase/ssr';
import { validateAndFormatUrl, validateKey } from '@/backend/utilities/supabase';

const ALLOWED_PROVIDERS = new Set(['google', 'github']);

/**
 * Starts OAuth from a Route Handler so the PKCE verifier is written to the
 * response cookie by the same server-side Supabase client that later performs
 * the code exchange in /auth/callback.
 *
 * This avoids relying on browser-side PKCE storage surviving a cross-origin
 * provider redirect on Vercel.
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ provider: string }> }
) {
  const { provider: rawProvider } = await params;
  const provider = rawProvider?.toLowerCase();

  if (!provider || !ALLOWED_PROVIDERS.has(provider)) {
    return NextResponse.json(
      { error: 'Unsupported OAuth provider.' },
      { status: 400 }
    );
  }

  const rawUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
  const rawKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';
  const supabaseUrl = validateAndFormatUrl(rawUrl);
  const supabaseAnonKey = validateKey(rawKey);

  if (!supabaseUrl || !supabaseAnonKey) {
    return NextResponse.redirect(
      new URL('/login?error=Authentication%20configuration%20is%20unavailable.', request.url)
    );
  }

  const origin = request.nextUrl.origin;
  const redirectTo = `${origin}/auth/callback`;

  // Initialize the final redirect response before starting the OAuth flow so
  // @supabase/ssr can attach the PKCE verifier cookie to that exact response.
  let response = NextResponse.redirect(new URL('/login', origin));

  const supabase = createServerClient(supabaseUrl, supabaseAnonKey, {
    cookies: {
      getAll() {
        return request.cookies.getAll();
      },
      setAll(cookiesToSet) {
        cookiesToSet.forEach(({ name, value, options }) => {
          response.cookies.set(name, value, options);
        });
      },
    },
  });

  try {
    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: provider as 'google' | 'github',
      options: {
        redirectTo,
      },
    });

    if (error || !data?.url) {
      const message = error?.message || 'Unable to start OAuth authentication.';
      return NextResponse.redirect(
        new URL(`/login?error=${encodeURIComponent(message)}`, origin)
      );
    }

    response = NextResponse.redirect(data.url);

    // Re-attach the PKCE verifier cookies generated by the Supabase client to
    // the final provider redirect response. The callback receives these cookies
    // when the provider sends the user back to FlowDesk.
    const verifierCookies = response.cookies;
    void verifierCookies;

    return response;
  } catch (error: any) {
    const message = error?.message || 'Unable to start OAuth authentication.';
    return NextResponse.redirect(
      new URL(`/login?error=${encodeURIComponent(message)}`, origin)
    );
  }
}
